name = "miniapp-scafolding"
main = "worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_GROUP_ID = "-1002500302980"
FRONTEND_URL = "https://miniapp-scafolding-2nv.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "hokm-db"
database_id = "f9b01d95-2b55-4787-9664-bb3d59c3f579"
[[migrations]]
tag = "v2"
deleted_classes = ["HokmGameRoom"]
